name: Github Actions

on:
  push:
    branches:
      - master

jobs:
  storybook:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Build
      run: npm run build-storybook
      env:
        CI: true
    - name: Pushes to another repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: ./storybook-static
        destination-github-username: 'sohanrao'
        destination-repository-name: 'try_actions_output'
        commit-message: See ORIGIN_COMMIT
    - name: Test get variable exported by try_actions
      run: echo $DESTINATION_CLONED_DIRECTORY
