name: Github Actions

on:
  push:
    branches:
      - main

jobs:
  storybook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Install
      run: npm install
    - name: Build storybook
      run: npm run build-storybook
